### ISSUE TITLE
Local install failure

### ISSUE THREAD

**Issue by dxps** [coolme200/webstorm-disable-index#4]
Hello,

I came to this problem while playing with [dva-boilerplate-isomorphic](https://github.com/sorrycc/dva-boilerplate-isomorphic) sample.
Although, the global installation (`npm install -g webstorm-disable-index`) works fine, the local installation fails completely: not even `webstorm-disable-index` directory gets created.

```
[ilema@visva dva-boilerplate-isomorphic]$ npm install

> webstorm-disable-index@1.1.1 postinstall /files/dev/react/dva/dva-boilerplate-isomorphic/node_modules/webstorm-disable-index
> node bin/webstorm-disable-index.js

[webstorm-disable-index] /files/dev/react/dva/dva-boilerplate-isomorphic/node_modules/webstorm-disable-index
[webstorm-disable-index] write files at /files/dev/react/dva/dva-boilerplate-isomorphic/
TypeError: Cannot read property 'split' of undefined
    at Command.run (/files/dev/react/dva/dva-boilerplate-isomorphic/node_modules/webstorm-disable-index/lib/command.js:13:44)
    at next (native)
    at onFulfilled (/files/dev/react/dva/dva-boilerplate-isomorphic/node_modules/co/index.js:65:19)
    at /files/dev/react/dva/dva-boilerplate-isomorphic/node_modules/co/index.js:54:5
    at co (/files/dev/react/dva/dva-boilerplate-isomorphic/node_modules/co/index.js:50:10)
    at toPromise (/files/dev/react/dva/dva-boilerplate-isomorphic/node_modules/co/index.js:118:63)
    at next (/files/dev/react/dva/dva-boilerplate-isomorphic/node_modules/co/index.js:99:29)
    at onFulfilled (/files/dev/react/dva/dva-boilerplate-isomorphic/node_modules/co/index.js:69:7)
    at /files/dev/react/dva/dva-boilerplate-isomorphic/node_modules/co/index.js:54:5
    at co (/files/dev/react/dva/dva-boilerplate-isomorphic/node_modules/co/index.js:50:10)
npm ERR! Darwin 16.3.0
npm ERR! argv "/Users/ilema/.nvm/versions/node/v6.9.1/bin/node" "/Users/ilema/.nvm/versions/node/v6.9.1/bin/npm" "install"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! webstorm-disable-index@1.1.1 postinstall: `node bin/webstorm-disable-index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webstorm-disable-index@1.1.1 postinstall script 'node bin/webstorm-disable-index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webstorm-disable-index package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/webstorm-disable-index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webstorm-disable-index
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webstorm-disable-index
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /files/dev/react/dva/dva-boilerplate-isomorphic/npm-debug.log
[ilema@visva dva-boilerplate-isomorphic]$
```

Any ideas, please?

Thank you!

**Comment by atian25** [comment]
```js
    this.pkgInfo = this.getPkgInfo();
    this.appName = _.last(this.pkgInfo.name.split('/'));
```

package.json is missing?

**Comment by dxps** [comment]
`package.json` exists, but it has no `name` property. So, this should be the problem...
[This](https://github.com/sorrycc/dva-boilerplate-isomorphic/blob/master/package.json) is the package.json used in this context.

**Comment by atian25** [comment]
so raise a PR to dva-boilerplate-isomorphic ?
a valid package.json should include `name`

**Comment by atian25** [comment]
@visvadw my mistake, see #5 , will release later

**Comment by atian25** [comment]
1.1.2
